# 暂时预留
#branch-defaults:
#  master:
#    environment: $FirstAppWitheb-env
#global:
#  application_name: First_App_withEB
#  default_ec2_keyname: first-key
#  default_platform: 64bit Amazon Linux 2017.09 v2.6.2 running Ruby 2.4 (Passenger Standalone)
#  default_region: us-east-2c
#  sc: git