version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - run: mvn dependency:go-offline


  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - Testing
      - run:
          name: MVN TEST
          command:  sh 'mvn test'


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
